name = "gps"
uuid = "4ce7606c-1bb5-4da1-9def-55850bdf6bd7"
authors = ["Calvin Lee <calvins.lee@utah.edu>", "Cole Perschon <cschon@cs.utah.edu>"]
version = "0.1.0"

[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterTools = "35a29f4d-8980-5a13-9543-d66fff28ecb8"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
